### ISSUE TITLE
STABS parsing support

### ISSUE THREAD

**Issue by JayFoxRox** [astrelsky/ghidra_mdebug#2]
Parsing the STABS seems to be the most critical portion about `.mdebug` for me.
The STABS parser already exists but is currently disabled here:

https://github.com/astrelsky/ghidra_mdebug/blob/4a7e67a3c566014da97b91145e682ff2cb1dfd78/src/main/java/mdebug/analysis/MdebugAnalyzer.java#L12
https://github.com/astrelsky/ghidra_mdebug/blob/4a7e67a3c566014da97b91145e682ff2cb1dfd78/src/main/java/mdebug/analysis/MdebugAnalyzer.java#L109-L117

There doesn't seem to be any information as to why it's not enabled.
- Why is it disabled?
- What's necessary to get it into a functional state?

**Comment by JayFoxRox** [comment]
> - Why is it disabled?

To answer my own question: STABS parsing is not upstream yet, and is being proposed by @astrelsky himself in https://github.com/NationalSecurityAgency/ghidra/pull/1460

> - What's necessary to get it into a functional state?

Probably improve upstream PR and aid with upstream review.

**Comment by astrelsky** [comment]
@VelocityRa I know you've played with it. You're input would be appreciated.

**Comment by VelocityRa** [comment]
Yes, @JayFoxRox I've merged @astrelsky's STABS parser onto this mdebug code, and made changes to it that allow it to skip defined types that result in exceptions (also handles things if they're referenced afterwards).

@astrelsky In what repo should this live? It requires that the `Ghidra_mdebug` tree is merged into the `Ghidra-Stabs` one, or the inverse. That's what I started with locally.

In the meantime, if you just want something to work with @JayFoxRox you can reach out to me on Discord `velocity#0042`. I've tried a few games with half a million STABS and it goes through them just fine (obviously misses some stuff, and there's a few other wrinkles with ie. virtual inheritance).
