### ISSUE TITLE
Provide prebuild extensions

### ISSUE THREAD

**Issue by JayFoxRox** [astrelsky/ghidra_mdebug#3]
I'm on Ghidra 9.2.4 and gradle 7.x; Unfortunately, these versions are incompatible, so I'm unable to build locally.
I don't have a good or easy option to install other versions of Gradle.

I can go to Ghidra 10-beta for gradle 7.x support, but then I can't use another required extension (https://github.com/beardypig/ghidra-emotionengine/issues/70). I'm also not sure if this plugin is Ghidra 10-beta compatible yet.

Having builds from CI would be a workaround.
It would also attract new people to try out the plugin, without them having to go through the trouble of compiling the extension first.
It also makes it easier to automate extension installation for projects which run Ghidra headless (as the user won't need to have a build-system locally).

**Comment by astrelsky** [comment]
You can take the `buildExtension.gradle` from the master repo and drop it in the Ghidra support folder. That should fix the gradle 7 issue. 

I have yet to ever play around with CI.

**Comment by JayFoxRox** [comment]
You should be able to copy-paste https://github.com/Cuyler36/CodeWarriorDemangler/pull/2 (where I basically took the files from https://github.com/beardypig/ghidra-emotionengine).
It uses https://github.com/er28-0652/setup-ghidra to install Ghidra by version number.

It's not the best CI script in the world, but it's better than not having any CI at all. The ability to create a best-effort nightly release for "latest" Ghidra would be very powerful (also see https://github.com/er28-0652/setup-ghidra/issues/14) to be informed of breaking changes in Ghidra.
