### ISSUE TITLE
Bad indentation

### ISSUE THREAD

**Issue by JayFoxRox** [astrelsky/ghidra_mdebug#4]
https://github.com/astrelsky/ghidra_mdebug/blob/4a7e67a3c566014da97b91145e682ff2cb1dfd78/src/main/java/mdebug/ecoff/EcoffPdr.java#L96-L110

Other instances could exist; I just noticed this while skimming over the code.

**Comment by astrelsky** [comment]
They should all be tabs. I will fix it when I get the chance.
