### ISSUE TITLE
`markupProcedure` does not markup function return type and parameters

### ISSUE THREAD

**Issue by JayFoxRox** [astrelsky/ghidra_mdebug#6]
Similar to #5; TIR from `pdr.getSymbol().getAuxu().getTir();` is not kept in any variable:

https://github.com/astrelsky/ghidra_mdebug/blob/00b07425a8335582177d9d610b3b1a22f5f67d49/src/main/java/mdebug/analysis/MdebugAnalyzer.java#L169-L171

Only `applyFunctionName` will be done and some source origin information is being added:

https://github.com/astrelsky/ghidra_mdebug/blob/00b07425a8335582177d9d610b3b1a22f5f67d49/src/main/java/mdebug/analysis/MdebugAnalyzer.java#L195-L200

However, critically, parameters and return type don't seem to get set, so the function signature remains incomplete.

---

I believe that `pdr.getSymbol().getAuxu().getTir();` is incorrect, because the document linked from the README says:

```
"Proc",
/* stProc 6 */
[...]
In AUX: first record is isym (symbol table index
  of symbol after the Proc end)
  Next is function type
```

which also matches the example from the same document (where "first record" aux+0 [=15] is `0x00000006` = isym for end after "Proc" end; and "next is" aux+1 [=16] is `0x06000000` which is TIR for `int` - the return type of `main`).

**Comment by astrelsky** [comment]
This is something I was never able to understand from the documentation. I'll reread this when I have a clearer head to see if you're explanation makes sense and if not I'll ask for further clarification.

**Comment by JayFoxRox** [comment]
From the documentation I understand how this is supposed to work, however, I have trouble finding actual real-world use cases of this. I might have some later, though.

Typically the files that I'm looking at contain stabs-in-ecoff. I mentioned this in https://github.com/astrelsky/ghidra_mdebug/issues/8#issuecomment-860182068.
With stabs-in-ecoff, almost all data is moved into the stabs.

With stabs-in-ecoff it seems like the ECOFF is primarily used as index for the stabs + to store line number and block structure information.
The files I'm looking at don't have any PARAM, LOCAL, ... types, instead the corresponding symbols are all type 0 with the data in the stabs.
