### ISSUE TITLE
Origin of `EcoffSymr.isStab()` check using `return (index & 0xFFF00) == 0x8F300;` isn't documented

### ISSUE THREAD

**Issue by JayFoxRox** [astrelsky/ghidra_mdebug#8]
This is being done here:

https://github.com/astrelsky/ghidra_mdebug/blob/00b07425a8335582177d9d610b3b1a22f5f67d49/src/main/java/mdebug/ecoff/EcoffSymr.java#L41
https://github.com/astrelsky/ghidra_mdebug/blob/00b07425a8335582177d9d610b3b1a22f5f67d49/src/main/java/mdebug/ecoff/EcoffSymr.java#L170-L172

I assume the top bits are some bitmask? But where is it documented / how did you find it?
It doesn't seem to match with the documentation for `SYMR` that is linked from the README.

**Comment by astrelsky** [comment]
It might have been in some gdb code somewhere. As you've said the documentation is extremely lacking.

I did recently come across some better documents. I'll link them when I get the chance.

**Comment by JayFoxRox** [comment]
[I found the documentation for this in binutils](https://github.com/bminor/binutils-gdb/blob/3451a2d7a3501e9c3fc344cbc4950c495f30c16d/include/coff/ecoff.h#L142-L146).
To enable this, [binutils, checks for a magic symbol](https://github.com/bminor/binutils-gdb/blob/3451a2d7a3501e9c3fc344cbc4950c495f30c16d/gdb/mdebugread.c#L2652-L2668).

Appropriate links should be added as a code comment probably.

**Comment by astrelsky** [comment]
> [I found the documentation for this in binutils](https://github.com/bminor/binutils-gdb/blob/3451a2d7a3501e9c3fc344cbc4950c495f30c16d/include/coff/ecoff.h#L142-L146).
> To enable this, [binutils, checks for a magic symbol](https://github.com/bminor/binutils-gdb/blob/3451a2d7a3501e9c3fc344cbc4950c495f30c16d/gdb/mdebugread.c#L2652-L2668).
> 
> Appropriate links should be added as a code comment probably.

Thank you. The reason it wasn't linked initially is probably because I had done it and then lost where I found the information.
